# AU-FISH Multi-Seed Individual Run

**Protocol:** `source_based`  
**Model:** `RT-DETR-L`  
**Seed:** `2026`  
**Experiment tag:** `multiseed_fullset_dedup_v1`

Notebook ini hanya menangani satu training run. Semua output disimpan pada folder
protocol, model, dan seed yang spesifik sehingga tidak bercampur dengan run lain.

Split dataset tidak diubah antar-seed. Preprocessing final tetap menggunakan:

- explicit image lists;
- filtered two-class annotations: coral and fish;
- exact duplicate removal yang telah dilakukan sebelumnya;
- minimum box width/height 5 px;
- minimum box area 25 px²;
- common filtered COCO ground truth.

Jangan mengubah protocol, model, seed, split, atau output root di tengah eksekusi.

In [ ]:
# CELL 1 — INSTALL PINNED DEPENDENCIES
!pip -q install ultralytics==8.4.102 pycocotools pandas pyyaml pillow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 1.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 23.2 MB/s eta 0:00:00

In [ ]:
# CELL 2 — MOUNT GOOGLE DRIVE
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
# CELL 3 — FIXED RUN CONFIGURATION
import contextlib
import hashlib
import io
import json
import os
import platform
import random
import shutil
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import yaml
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval

from ultralytics import RTDETR
MODEL_CLASS = RTDETR

PROTOCOL = "source_based"
MODEL_KEY = "rtdetr_l"
MODEL_LABEL = "RT-DETR-L"
SEED = 2026

PROJECT_ROOT = Path("/content/drive/MyDrive/au-fish/dataset_v2")
DATASET_ROOT = PROJECT_ROOT / PROTOCOL

INDIVIDUAL_TAG = "multiseed_fullset_dedup_v1"
LEGACY_FINAL_TAG = "simple_wbf_fullset_dedup_v1"

YAML_PATH = DATASET_ROOT / f"aufish_{PROTOCOL}_fullset.yaml"

TRAIN_RUN_ROOT = (
    DATASET_ROOT
    / "runs"
    / INDIVIDUAL_TAG
    / MODEL_KEY
    / f"seed_{SEED}"
)

EVAL_RUN_ROOT = (
    DATASET_ROOT
    / "runs_eval"
    / INDIVIDUAL_TAG
    / MODEL_KEY
    / f"seed_{SEED}"
)

EXPERIMENT_ROOT = (
    DATASET_ROOT
    / "experiment_logs"
    / INDIVIDUAL_TAG
)

RUN_ROOT = (
    EXPERIMENT_ROOT
    / "individual"
    / MODEL_KEY
    / f"seed_{SEED}"
)

RAW_DIR = RUN_ROOT / "raw_predictions"
RESULTS_DIR = RUN_ROOT / "results"
MANIFEST_DIR = RUN_ROOT / "manifests"
SHARED_GT_DIR = EXPERIMENT_ROOT / "shared_ground_truth"

for path in [
    TRAIN_RUN_ROOT,
    EVAL_RUN_ROOT,
    RAW_DIR,
    RESULTS_DIR,
    MANIFEST_DIR,
    SHARED_GT_DIR,
]:
    path.mkdir(parents=True, exist_ok=True)

PRETRAINED_WEIGHTS = "rtdetr-l.pt"
EPOCHS = 50
IMAGE_SIZE = 640
TRAIN_BATCH = 4
PREDICT_BATCH = 1
DEVICE = 0 if torch.cuda.is_available() else "cpu"

TRAIN_RUN_NAME = "train"
TRAIN_OUTPUT_DIR = TRAIN_RUN_ROOT / TRAIN_RUN_NAME
BEST_CHECKPOINT = TRAIN_OUTPUT_DIR / "weights" / "best.pt"

FORCE_RETRAIN = False
FORCE_REINFERENCE = False

EXPECTED_IMAGES = {
    "time_based": {"train": 1061, "val": 203, "test": 282},
    "source_based": {"train": 1083, "val": 232, "test": 231},
}

print("=" * 80)
print("AU-FISH MULTI-SEED INDIVIDUAL RUN")
print("Protocol :", PROTOCOL)
print("Model    :", MODEL_LABEL)
print("Seed     :", SEED)
print("Run root :", RUN_ROOT)
print("GPU      :", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU")
print("=" * 80)

Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
================================================================================
AU-FISH MULTI-SEED INDIVIDUAL RUN
Protocol : source_based
Model    : RT-DETR-L
Seed     : 2026
Run root : /content/drive/MyDrive/au-fish/dataset_v2/source_based/experiment_logs/multiseed_fullset_dedup_v1/individual/rtdetr_l/seed_2026
GPU      : Tesla T4
================================================================================

In [ ]:
# CELL 4 — REPRODUCIBILITY AND FILE HELPERS
def set_global_seed(seed):
    os.environ["PYTHONHASHSEED"] = str(seed)

    random.seed(seed)
    np.random.seed(seed)

    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def sha256_file(path, chunk_size=1024 * 1024):
    digest = hashlib.sha256()

    with open(path, "rb") as file:
        while True:
            chunk = file.read(chunk_size)

            if not chunk:
                break

            digest.update(chunk)

    return digest.hexdigest()


def load_json(path):
    with open(path, "r", encoding="utf-8") as file:
        return json.load(file)


def save_json(data, path):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    temporary = path.with_suffix(path.suffix + ".tmp")

    with open(temporary, "w", encoding="utf-8") as file:
        json.dump(
            data,
            file,
            ensure_ascii=False,
            indent=2,
        )

    temporary.replace(path)


def save_run_config():
    config = {
        "protocol": PROTOCOL,
        "model": MODEL_KEY,
        "seed": SEED,
        "experiment_tag": INDIVIDUAL_TAG,
        "dataset_yaml": str(YAML_PATH),
        "pretrained_weights": PRETRAINED_WEIGHTS,
        "epochs": EPOCHS,
        "image_size": IMAGE_SIZE,
        "train_batch": TRAIN_BATCH,
        "predict_batch": PREDICT_BATCH,
        "deterministic": True,
        "raw_prediction_confidence": 0.001,
        "raw_prediction_iou": 0.70,
        "raw_prediction_max_det": 300,
        "test_time_augmentation": False,
        "checkpoint_selection": "Ultralytics validation fitness",
    }

    save_json(
        config,
        MANIFEST_DIR / "run_config.json",
    )


set_global_seed(SEED)
save_run_config()
print("Global seed set:", SEED)

Global seed set: 2026

In [ ]:
# CELL 5 — DATASET AND SHARED GROUND-TRUTH PREFLIGHT
if not YAML_PATH.exists():
    raise FileNotFoundError(
        f"Final explicit-list YAML not found: {YAML_PATH}"
    )

with open(YAML_PATH, "r", encoding="utf-8") as file:
    data_yaml = yaml.safe_load(file)

required_yaml_keys = {"train", "val", "test", "names"}

if not required_yaml_keys.issubset(data_yaml):
    raise RuntimeError(
        f"YAML missing keys: {required_yaml_keys - set(data_yaml)}"
    )

for split_name in ["train", "val", "test"]:
    list_path = Path(data_yaml[split_name])

    if not list_path.exists():
        raise FileNotFoundError(
            f"Explicit image list not found: {list_path}"
        )

    image_paths = [
        line.strip()
        for line in list_path.read_text(
            encoding="utf-8"
        ).splitlines()
        if line.strip()
    ]

    expected = EXPECTED_IMAGES[PROTOCOL][split_name]

    if len(image_paths) != expected:
        raise RuntimeError(
            f"{split_name}: expected {expected} images, "
            f"found {len(image_paths)}"
        )

    if len(image_paths) != len(set(image_paths)):
        raise RuntimeError(
            f"{split_name}: duplicate paths found"
        )

    missing = [
        path
        for path in image_paths
        if not Path(path).exists()
    ]

    if missing:
        raise FileNotFoundError(
            f"{split_name}: {len(missing)} image files missing. "
            f"First: {missing[0]}"
        )

    print(
        f"✅ {split_name}: {len(image_paths)} explicit paths"
    )

legacy_gt_dir = (
    DATASET_ROOT
    / "experiment_logs"
    / LEGACY_FINAL_TAG
    / "shared_ground_truth"
)

gt_files = {
    "validation": "val_gt_filtered.json",
    "test": "test_gt_filtered.json",
}

for split_label, file_name in gt_files.items():
    source_path = legacy_gt_dir / file_name
    target_path = SHARED_GT_DIR / file_name

    if not source_path.exists():
        raise FileNotFoundError(
            f"Locked common GT not found: {source_path}"
        )

    if not target_path.exists():
        shutil.copy2(source_path, target_path)

    gt = load_json(target_path)
    expected = EXPECTED_IMAGES[PROTOCOL][
        "val" if split_label == "validation" else "test"
    ]

    if len(gt["images"]) != expected:
        raise RuntimeError(
            f"{split_label} GT image count mismatch: "
            f"{len(gt['images'])} != {expected}"
        )

    print(
        f"✅ {split_label} GT: "
        f"{len(gt['images'])} images, "
        f"{len(gt['annotations'])} annotations"
    )

✅ train: 1083 explicit paths
✅ val: 232 explicit paths
✅ test: 231 explicit paths
✅ validation GT: 232 images, 1857 annotations
✅ test GT: 231 images, 1820 annotations

In [ ]:
# CELL 6 — TRAIN RT-DETR-L
if BEST_CHECKPOINT.exists() and not FORCE_RETRAIN:
    print("Checkpoint already exists. Training skipped:")
    print(BEST_CHECKPOINT)
else:
    if TRAIN_OUTPUT_DIR.exists() and FORCE_RETRAIN:
        shutil.rmtree(TRAIN_OUTPUT_DIR)

    model = MODEL_CLASS(PRETRAINED_WEIGHTS)

    train_result = model.train(
        data=str(YAML_PATH),
        epochs=EPOCHS,
        imgsz=IMAGE_SIZE,
        batch=TRAIN_BATCH,
        device=DEVICE,
        seed=SEED,
        deterministic=True,
        project=str(TRAIN_RUN_ROOT),
        name=TRAIN_RUN_NAME,
        exist_ok=False,
        resume=False,
        verbose=True,
    )

if not BEST_CHECKPOINT.exists():
    raise FileNotFoundError(
        f"Best checkpoint not produced: {BEST_CHECKPOINT}"
    )

print("✅ Best checkpoint:", BEST_CHECKPOINT)
print("SHA256:", sha256_file(BEST_CHECKPOINT))

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/rtdetr-l.pt to 'rtdetr-l.pt': 100% ━━━━━━━━━━━━ 63.4MB 141.3MB/s 0.4s
New https://pypi.org/project/ultralytics/8.4.108 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.4.102 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/au-fish/dataset_v2/source_based/aufish_source_based_fullset.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dis=6.0, distill_model=None, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=rtdetr-l.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/au-fish/dataset_v2/source_based/runs/multiseed_fullset_dedup_v1/rtdetr_l/seed_2026, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/.shortcut-targets-by-id/1kW1zeaSZ1KWylT60LjX9VMVZYNBF137Z/au-fish/dataset_v2/source_based/runs/multiseed_fullset_dedup_v1/rtdetr_l/seed_2026/train, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=2026, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 16.9MB/s 0.0s
Overriding model.yaml nc=80 with nc=2
WARNING ⚠️ no model scale passed. Assuming scale='l'.

                   from  n    params  module                                       arguments
  0                  -1  1     25248  ultralytics.nn.modules.block.HGStem          [3, 32, 48]
  1                  -1  6    155072  ultralytics.nn.modules.block.HGBlock         [48, 48, 128, 3, 6]
  2                  -1  1      1408  ultralytics.nn.modules.conv.DWConv           [128, 128, 3, 2, 1, False]
  3                  -1  6    839296  ultralytics.nn.modules.block.HGBlock         [128, 96, 512, 3, 6]
  4                  -1  1      5632  ultralytics.nn.modules.conv.DWConv           [512, 512, 3, 2, 1, False]
  5                  -1  6   1695360  ultralytics.nn.modules.block.HGBlock         [512, 192, 1024, 5, 6, True, False]
  6                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  7                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  8                  -1  1     11264  ultralytics.nn.modules.conv.DWConv           [1024, 1024, 3, 2, 1, False]
  9                  -1  6   6708480  ultralytics.nn.modules.block.HGBlock         [1024, 384, 2048, 5, 6, True, False]
 10                  -1  1    524800  ultralytics.nn.modules.conv.Conv             [2048, 256, 1, 1, None, 1, 1, False]
 11                  -1  1    789760  ultralytics.nn.modules.transformer.AIFI      [256, 1024, 8]
 12                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14                   7  1    262656  ultralytics.nn.modules.conv.Conv             [1024, 256, 1, 1, None, 1, 1, False]
 15            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 17                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 18                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 19                   3  1    131584  ultralytics.nn.modules.conv.Conv             [512, 256, 1, 1, None, 1, 1, False]
 20            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 22                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 23            [-1, 17]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 24                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 25                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 26            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 27                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 28        [21, 24, 27]  1   7305962  ultralytics.nn.modules.head.RTDETRDecoder    [2, [256, 256, 256]]
rt-detr-l summary: 465 layers, 32,810,186 parameters, 32,810,186 gradients, 108.0 GFLOPs

Transferred 926/941 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 70.3MB/s 0.1s
AMP: checks passed ✅
WARNING ⚠️ train: Slow image access detected (ping: 0.6±0.1 ms, read: 7.4±3.2 MB/s, size: 3910.5 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
train: Scanning /content/drive/.shortcut-targets-by-id/1kW1zeaSZ1KWylT60LjX9VMVZYNBF137Z/au-fish/dataset_v2/source_based/train/labels.cache... 1083 images, 26 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1083/1083 267.2Mit/s 0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
WARNING ⚠️ val: Slow image access detected (ping: 0.9±0.6 ms, read: 8.6±3.0 MB/s, size: 3792.2 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning /content/drive/.shortcut-targets-by-id/1kW1zeaSZ1KWylT60LjX9VMVZYNBF137Z/au-fish/dataset_v2/source_based/val/labels.cache... 232 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 232/232 12.8Mit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001667, momentum=0.9) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
Plotting labels to /content/drive/.shortcut-targets-by-id/1kW1zeaSZ1KWylT60LjX9VMVZYNBF137Z/au-fish/dataset_v2/source_based/runs/multiseed_fullset_dedup_v1/rtdetr_l/seed_2026/train/labels.jpg...
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /content/drive/.shortcut-targets-by-id/1kW1zeaSZ1KWylT60LjX9VMVZYNBF137Z/au-fish/dataset_v2/source_based/runs/multiseed_fullset_dedup_v1/rtdetr_l/seed_2026/train
Starting training for 50 epochs...

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       1/50      3.42G       1.41      2.701     0.6199         60        640: 0% ──────────── 0/271  6.8s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       1/50      3.65G     0.8819      1.545     0.4945         18        640: 100% ━━━━━━━━━━━━ 271/271 2.1it/s 2:11
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 3.4it/s 8.4s
                   all        232       1857      0.518      0.441      0.418      0.249

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       2/50      3.84G      0.732     0.5758     0.3022         15        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       2/50      3.84G     0.7172     0.6687     0.3521         26        640: 100% ━━━━━━━━━━━━ 271/271 2.6it/s 1:43
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.0it/s 5.8s
                   all        232       1857      0.415      0.321      0.279      0.156

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       3/50      3.84G     0.5655      0.695     0.1657         21        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       3/50      3.85G     0.7264     0.7083     0.3482         32        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:42
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 4.7it/s 6.2s
                   all        232       1857      0.398      0.362      0.306      0.172

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       4/50      3.85G     0.5704      0.836     0.2237         16        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       4/50      3.85G       0.69     0.7102     0.3401         68        640: 100% ━━━━━━━━━━━━ 271/271 2.6it/s 1:43
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.0it/s 5.8s
                   all        232       1857      0.475      0.354      0.353      0.211

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       5/50      3.85G     0.5122     0.5656     0.3112         23        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       5/50      3.85G     0.6817     0.6955     0.3109         26        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:42
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 4.9it/s 5.9s
                   all        232       1857      0.381      0.414      0.336      0.212

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       6/50      3.85G     0.6404      0.614     0.2325         31        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       6/50      3.85G     0.6411     0.6855     0.2958         18        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:42
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 4.8it/s 6.0s
                   all        232       1857      0.453      0.448      0.385      0.215

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       7/50      3.85G     0.8393     0.5832     0.3481         33        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       7/50      3.85G     0.6338     0.7041     0.2936         30        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:42
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.0it/s 5.8s
                   all        232       1857        0.5      0.344      0.334      0.188

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       8/50      3.85G     0.4988     0.9113     0.2317         33        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       8/50      3.85G     0.6301     0.6546     0.2897         13        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:42
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.0it/s 5.8s
                   all        232       1857      0.486      0.444      0.428      0.257

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       9/50      3.85G     0.3152     0.5721     0.1711         11        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       9/50      3.85G     0.5717     0.6517     0.2724         22        640: 100% ━━━━━━━━━━━━ 271/271 2.6it/s 1:42
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.1it/s 5.7s
                   all        232       1857      0.439      0.377      0.337      0.209

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      10/50      3.85G     0.3816     0.7235     0.2483         17        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      10/50      3.85G     0.5878     0.6517     0.2579          7        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:41
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.3it/s 5.5s
                   all        232       1857      0.438      0.489      0.413      0.249

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      11/50      3.85G     0.5867     0.5623     0.2608         26        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      11/50      4.11G     0.5595     0.6474      0.252          6        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:41
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.1it/s 5.7s
                   all        232       1857       0.44      0.429      0.374      0.208

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      12/50      4.11G     0.8794     0.4339      0.104         63        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      12/50      4.11G     0.5628     0.6094     0.2608         14        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:41
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.2it/s 5.6s
                   all        232       1857      0.422      0.387      0.348      0.201

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      13/50      4.11G     0.3001     0.6751     0.1861         21        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      13/50      4.11G     0.5391     0.6144     0.2576         23        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:41
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.2it/s 5.6s
                   all        232       1857      0.447      0.406      0.348      0.202

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      14/50      4.11G     0.3428      0.603     0.3106         10        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      14/50      4.11G     0.5408     0.5903     0.2455         18        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:41
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.2it/s 5.6s
                   all        232       1857      0.458      0.378      0.337      0.189

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      15/50      4.11G     0.6969     0.4966     0.1863         31        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      15/50      4.11G     0.5102     0.5849     0.2258         23        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:41
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.0it/s 5.8s
                   all        232       1857      0.456      0.435       0.39      0.238

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      16/50      4.11G     0.7858     0.5253     0.3192         29        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      16/50      4.11G     0.5203     0.5762     0.2211          8        640: 100% ━━━━━━━━━━━━ 271/271 2.6it/s 1:42
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.1it/s 5.7s
                   all        232       1857      0.443       0.45      0.368      0.213

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      17/50      4.11G     0.3097     0.8667     0.2353         11        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      17/50      4.11G     0.5036     0.5874     0.2208         99        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:42
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.0it/s 5.8s
                   all        232       1857       0.49      0.444      0.417      0.256

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      18/50      4.11G     0.6276     0.5582     0.3911         19        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      18/50      4.34G     0.5035     0.5762     0.2312          7        640: 100% ━━━━━━━━━━━━ 271/271 2.6it/s 1:46
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.0it/s 5.8s
                   all        232       1857      0.469      0.456      0.392      0.226

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      19/50      4.34G     0.3028     0.7436     0.1803         19        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      19/50      4.34G     0.4959     0.5683     0.2159         23        640: 100% ━━━━━━━━━━━━ 271/271 2.6it/s 1:44
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.1it/s 5.6s
                   all        232       1857      0.381      0.451      0.349      0.199

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      20/50      4.34G      1.278      0.378     0.2292         65        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      20/50      4.34G     0.5015     0.5516     0.2116         13        640: 100% ━━━━━━━━━━━━ 271/271 2.6it/s 1:44
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 4.9it/s 5.9s
                   all        232       1857      0.499      0.431      0.382      0.234

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      21/50      4.34G       0.22     0.5035     0.1526          9        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      21/50      4.34G     0.4743     0.5769     0.2121         17        640: 100% ━━━━━━━━━━━━ 271/271 2.6it/s 1:44
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.1it/s 5.7s
                   all        232       1857      0.494      0.472      0.447      0.297

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      22/50      4.34G     0.7022     0.4421     0.2902         43        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      22/50      4.34G      0.489     0.5427     0.1991         37        640: 100% ━━━━━━━━━━━━ 271/271 2.6it/s 1:44
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 4.9it/s 5.9s
                   all        232       1857      0.484      0.384      0.381      0.245

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      23/50      4.34G     0.3763     0.4175     0.1395         23        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      23/50      4.34G     0.4806      0.555     0.2052          3        640: 100% ━━━━━━━━━━━━ 271/271 2.6it/s 1:45
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.0it/s 5.8s
                   all        232       1857      0.477       0.45      0.394      0.212

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      24/50      4.34G     0.5517     0.6358     0.2922         17        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      24/50      4.34G     0.4731     0.5369      0.199         93        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:42
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.1it/s 5.7s
                   all        232       1857      0.563      0.408      0.394      0.242

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      25/50      4.34G     0.2155     0.3202     0.1134         17        640: 0% ──────────── 0/271  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      25/50      4.34G     0.4566     0.5551      0.194         34        640: 100% ━━━━━━━━━━━━ 271/271 2.6it/s 1:42
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 4.9it/s 6.0s
                   all        232       1857      0.458      0.432      0.351      0.188

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      26/50      4.34G      0.473     0.5741     0.2849         16        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      26/50      4.34G     0.4798     0.5396     0.2023         50        640: 100% ━━━━━━━━━━━━ 271/271 2.6it/s 1:42
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.0it/s 5.8s
                   all        232       1857       0.44      0.471      0.391      0.242

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      27/50      4.34G     0.5566     0.6284     0.2291         26        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      27/50      4.34G     0.4518     0.5287     0.2013         38        640: 100% ━━━━━━━━━━━━ 271/271 2.6it/s 1:42
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 4.8it/s 6.0s
                   all        232       1857      0.517      0.451      0.414      0.238

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      28/50      4.34G     0.5002     0.5411     0.2098         21        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      28/50      4.34G     0.4522     0.5285      0.193         31        640: 100% ━━━━━━━━━━━━ 271/271 2.6it/s 1:42
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.1it/s 5.7s
                   all        232       1857      0.499      0.437      0.385      0.221

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      29/50      4.34G     0.6589     0.5678     0.1373         24        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      29/50      4.34G     0.4595     0.5093      0.194         14        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:41
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.1it/s 5.7s
                   all        232       1857      0.466      0.378       0.34      0.209

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      30/50      4.34G     0.2399     0.5006      0.125         10        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      30/50      4.34G     0.4322     0.5127       0.18          4        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:41
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.1it/s 5.7s
                   all        232       1857       0.37      0.378       0.32      0.195

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      31/50      4.34G     0.3802     0.5906     0.1885         13        640: 0% ──────────── 0/271  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      31/50      4.34G     0.4483     0.5065     0.1814         15        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:41
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.1it/s 5.7s
                   all        232       1857       0.49      0.388      0.395      0.273

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      32/50      4.34G     0.4016     0.4633     0.3161         18        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      32/50      4.34G     0.4348     0.4915     0.1816         12        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:41
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.2it/s 5.6s
                   all        232       1857      0.497      0.382      0.355      0.233

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      33/50      4.34G       0.25     0.5455     0.1051         19        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      33/50      4.34G     0.4105     0.5013     0.1785         17        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:40
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.0it/s 5.8s
                   all        232       1857      0.472      0.465      0.404      0.271

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      34/50      4.34G     0.7476     0.4349     0.1597         45        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      34/50      4.34G     0.4157     0.4855     0.1731         15        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:41
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.2it/s 5.6s
                   all        232       1857       0.58       0.37      0.381      0.252

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      35/50      4.34G     0.3713      0.425     0.2195         23        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      35/50      4.34G     0.4339     0.4963     0.1757          9        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:40
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.2it/s 5.6s
                   all        232       1857       0.51      0.387       0.37       0.23

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      36/50      4.34G     0.4326     0.5885      0.166         15        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      36/50      4.34G     0.4241     0.5012     0.1781         19        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:40
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.3it/s 5.5s
                   all        232       1857      0.494      0.437      0.407      0.246

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      37/50      4.34G     0.3686     0.4462     0.2829         11        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      37/50      4.34G     0.4242     0.5036      0.186         10        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:40
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.2it/s 5.6s
                   all        232       1857      0.508      0.467      0.402      0.252

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      38/50      4.34G     0.5088     0.5323    0.08416         45        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      38/50      4.34G      0.417     0.4884     0.1699         11        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:41
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.2it/s 5.6s
                   all        232       1857      0.537      0.382      0.388       0.26

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      39/50      4.34G     0.3708     0.4654     0.3719         14        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      39/50      4.34G     0.4151     0.4827     0.1727         41        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:40
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.3it/s 5.5s
                   all        232       1857      0.524      0.369      0.366      0.251

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      40/50      4.34G     0.3407     0.4674     0.1158         45        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      40/50      4.34G     0.4205     0.4835     0.1788          6        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:40
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.1it/s 5.7s
                   all        232       1857      0.455      0.435      0.356      0.206
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      41/50      4.34G     0.1313     0.3294    0.07519          5        640: 0% ──────────── 0/271  0.9s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      41/50      4.34G     0.3381     0.4558     0.1599          9        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:42
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.2it/s 5.6s
                   all        232       1857      0.488      0.469      0.404       0.25

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      42/50      4.34G     0.5421     0.4546    0.07327         85        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      42/50      4.34G      0.337     0.4414     0.1541         42        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:40
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 4.9it/s 5.9s
                   all        232       1857      0.507      0.411      0.373      0.228

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      43/50      4.34G      0.186     0.2741     0.1329          7        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      43/50      4.34G     0.3399     0.4255     0.1532         16        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:40
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.2it/s 5.6s
                   all        232       1857      0.485      0.417      0.377      0.236

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      44/50      4.34G     0.2829      0.423    0.09464         28        640: 0% ──────────── 0/271  0.3s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      44/50      4.34G      0.319     0.4218      0.149         10        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:40
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.2it/s 5.6s
                   all        232       1857       0.47      0.386       0.35      0.211

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      45/50      4.34G     0.2476     0.3608     0.0615          8        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      45/50      4.34G      0.322     0.4061     0.1417         40        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:40
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.2it/s 5.6s
                   all        232       1857      0.465      0.364       0.33      0.209

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      46/50      4.34G     0.1936     0.3234    0.09188         12        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      46/50      4.34G     0.3259     0.4078     0.1392          5        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:40
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.2it/s 5.6s
                   all        232       1857      0.456      0.416      0.366      0.235

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      47/50      4.34G     0.3211     0.4056    0.09317         26        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      47/50      4.34G     0.3204     0.4049     0.1386         35        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:40
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.1it/s 5.7s
                   all        232       1857      0.447      0.404      0.338      0.209

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      48/50      4.34G     0.3925     0.5896     0.1233         42        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      48/50      4.34G      0.311     0.3971     0.1327          3        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:40
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.2it/s 5.6s
                   all        232       1857      0.538      0.381      0.368      0.228

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      49/50      4.34G     0.1279     0.2335     0.1071          5        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      49/50      4.34G     0.2994     0.3853     0.1359         11        640: 100% ━━━━━━━━━━━━ 271/271 2.7it/s 1:40
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.2it/s 5.6s
                   all        232       1857      0.486      0.416      0.373       0.23

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      50/50      4.34G     0.3281     0.3335     0.1527         10        640: 0% ──────────── 0/271  0.4s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:869: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      50/50      4.34G     0.2988     0.3848     0.1254         13        640: 100% ━━━━━━━━━━━━ 271/271 2.6it/s 1:46
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 5.0it/s 5.8s
                   all        232       1857      0.559      0.365      0.361      0.222

50 epochs completed in 1.521 hours.
Optimizer stripped from /content/drive/.shortcut-targets-by-id/1kW1zeaSZ1KWylT60LjX9VMVZYNBF137Z/au-fish/dataset_v2/source_based/runs/multiseed_fullset_dedup_v1/rtdetr_l/seed_2026/train/weights/last.pt, 66.2MB
Optimizer stripped from /content/drive/.shortcut-targets-by-id/1kW1zeaSZ1KWylT60LjX9VMVZYNBF137Z/au-fish/dataset_v2/source_based/runs/multiseed_fullset_dedup_v1/rtdetr_l/seed_2026/train/weights/best.pt, 66.2MB

Validating /content/drive/.shortcut-targets-by-id/1kW1zeaSZ1KWylT60LjX9VMVZYNBF137Z/au-fish/dataset_v2/source_based/runs/multiseed_fullset_dedup_v1/rtdetr_l/seed_2026/train/weights/best.pt...
Ultralytics 8.4.102 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
rt-detr-l summary: 310 layers, 31,987,850 parameters, 0 gradients, 103.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 29/29 4.4it/s 6.6s
                   all        232       1857      0.499      0.467      0.447      0.297
                 coral        162        288       0.48      0.594      0.552      0.402
                  fish        107       1569      0.517       0.34      0.342      0.191
Speed: 0.2ms preprocess, 22.5ms inference, 0.0ms loss, 1.0ms postprocess per image
Results saved to /content/drive/.shortcut-targets-by-id/1kW1zeaSZ1KWylT60LjX9VMVZYNBF137Z/au-fish/dataset_v2/source_based/runs/multiseed_fullset_dedup_v1/rtdetr_l/seed_2026/train
✅ Best checkpoint: /content/drive/MyDrive/au-fish/dataset_v2/source_based/runs/multiseed_fullset_dedup_v1/rtdetr_l/seed_2026/train/weights/best.pt
SHA256: adffcd97228637fe4766f5550c38bea2301b01e99bc78695807d560ae21b36d9

In [10]:
# ============================================================
# CLEAN GPU MEMORY BEFORE RT-DETR TEST INFERENCE
# ============================================================
import gc
import torch

objects_to_delete = [
    "model",
    "trained_model",
    "inference_model",
    "train_result",
    "metrics",
    "results",
    "result",
]

for object_name in objects_to_delete:
    if object_name in globals():
        del globals()[object_name]
        print(f"Deleted: {object_name}")

gc.collect()

if torch.cuda.is_available():
    torch.cuda.empty_cache()

    try:
        torch.cuda.ipc_collect()
    except Exception:
        pass

    allocated = torch.cuda.memory_allocated() / 1024**3
    reserved = torch.cuda.memory_reserved() / 1024**3
    free, total = torch.cuda.mem_get_info()

    print(f"Allocated : {allocated:.2f} GiB")
    print(f"Reserved  : {reserved:.2f} GiB")
    print(f"Free GPU  : {free / 1024**3:.2f} GiB")
    print(f"Total GPU : {total / 1024**3:.2f} GiB")

Deleted: model
Deleted: trained_model
Deleted: inference_model
Deleted: train_result
Deleted: metrics
Allocated : 6.93 GiB
Reserved  : 7.01 GiB
Free GPU  : 7.35 GiB
Total GPU : 14.56 GiB

In [ ]:
# CELL 7 — FRAMEWORK-NATIVE VALIDATION AND TEST DIAGNOSTICS
diagnostic_rows = []

trained_model = MODEL_CLASS(str(BEST_CHECKPOINT))

for split_name in ["val", "test"]:
    output_name = f"{split_name}_diagnostic"

    metrics = trained_model.val(
        data=str(YAML_PATH),
        split=split_name,
        imgsz=IMAGE_SIZE,
        batch=PREDICT_BATCH,
        device=DEVICE,
        project=str(EVAL_RUN_ROOT),
        name=output_name,
        exist_ok=True,
        verbose=True,
    )

    row = {
        "protocol": PROTOCOL,
        "model": MODEL_KEY,
        "seed": SEED,
        "split": split_name,
        "mAP50_95": float(metrics.box.map),
        "mAP50": float(metrics.box.map50),
        "mAP75": float(metrics.box.map75),
        "AP_coral": float(metrics.box.maps[0]),
        "AP_fish": float(metrics.box.maps[1]),
    }

    diagnostic_rows.append(row)

diagnostic_df = pd.DataFrame(diagnostic_rows)
diagnostic_df.to_csv(
    RESULTS_DIR / "framework_native_results.csv",
    index=False,
)

display(diagnostic_df)

Ultralytics 8.4.102 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
rt-detr-l summary: 310 layers, 31,987,850 parameters, 0 gradients, 103.4 GFLOPs
val: Fast image access ✅ (ping: 0.5±0.1 ms, read: 839.3±46.9 MB/s, size: 3789.3 KB)
val: Scanning /content/drive/.shortcut-targets-by-id/1kW1zeaSZ1KWylT60LjX9VMVZYNBF137Z/au-fish/dataset_v2/source_based/val/labels.cache... 232 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 232/232 64.9Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 232/232 14.8it/s 15.6s
                   all        232       1857      0.494      0.465      0.446      0.297
                 coral        162        288      0.477       0.59       0.55      0.404
                  fish        107       1569      0.512       0.34      0.342      0.191
Speed: 1.9ms preprocess, 57.7ms inference, 0.0ms loss, 0.5ms postprocess per image
Results saved to /content/drive/.shortcut-targets-by-id/1kW1zeaSZ1KWylT60LjX9VMVZYNBF137Z/au-fish/dataset_v2/source_based/runs_eval/multiseed_fullset_dedup_v1/rtdetr_l/seed_2026/val_diagnostic
Ultralytics 8.4.102 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
rt-detr-l summary: 310 layers, 31,987,850 parameters, 0 gradients, 103.4 GFLOPs
WARNING ⚠️ val: Slow image access detected (ping: 0.8±0.2 ms, read: 9.3±6.2 MB/s, size: 3068.5 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning /content/drive/.shortcut-targets-by-id/1kW1zeaSZ1KWylT60LjX9VMVZYNBF137Z/au-fish/dataset_v2/source_based/test/labels.cache... 231 images, 11 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 231/231 48.4Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 231/231 9.7it/s 23.7s
                   all        231       1820      0.538      0.512      0.456      0.261
                 coral        132        437      0.449      0.577       0.44       0.27
                  fish        163       1383      0.627      0.448      0.472      0.253
Speed: 1.2ms preprocess, 57.1ms inference, 0.0ms loss, 0.5ms postprocess per image
Results saved to /content/drive/.shortcut-targets-by-id/1kW1zeaSZ1KWylT60LjX9VMVZYNBF137Z/au-fish/dataset_v2/source_based/runs_eval/multiseed_fullset_dedup_v1/rtdetr_l/seed_2026/test_diagnostic

,protocol,model,seed,split,mAP50_95,mAP50,mAP75,AP_coral,AP_fish
0,source_based,rtdetr_l,2026,val,0.297398,0.446474,0.316357,0.404033,0.190762
1,source_based,rtdetr_l,2026,test,0.261454,0.456054,0.252690,0.269723,0.253186

In [11]:
# CELL 8 — RAW PREDICTION AND COMMON COCOEVAL HELPERS
def blank_record(image_info):
    return {
        "image_id": int(image_info["id"]),
        "file_name": str(image_info["file_name"]),
        "width": int(image_info["width"]),
        "height": int(image_info["height"]),
        "boxes": [],
        "scores": [],
        "labels": [],
    }


def gt_path_for(split_label):
    file_name = (
        "val_gt_filtered.json"
        if split_label == "validation"
        else "test_gt_filtered.json"
    )

    return SHARED_GT_DIR / file_name


def split_dir_name(split_label):
    return "val" if split_label == "validation" else "test"


def build_ordered_image_paths(gt):
    split_dir = split_dir_name(CURRENT_SPLIT)

    paths = []

    for image_info in gt["images"]:
        path = (
            DATASET_ROOT
            / split_dir
            / "images"
            / image_info["file_name"]
        )

        if not path.exists():
            raise FileNotFoundError(
                f"Image missing: {path}"
            )

        paths.append(str(path))

    return paths


# ============================================================
# MEMORY-SAFE RT-DETR RAW INFERENCE
# Single-image streaming + partial resume
# ============================================================
import gc
from pathlib import Path


def run_raw_inference(model, split_label):
    """
    Memory-safe raw prediction.

    Fitur:
    - menggunakan satu gambar per inference;
    - tidak mengumpulkan seluruh Results di memori;
    - menyimpan progress sementara;
    - dapat dilanjutkan setelah runtime terputus;
    - mapping menggunakan urutan COCO ground truth;
    - validation/test final yang sudah lengkap akan dipakai ulang.
    """
    gt_path = gt_path_for(split_label)
    gt = load_json(gt_path)

    image_infos = gt["images"]

    split_directory = (
        "val"
        if split_label == "validation"
        else "test"
    )

    output_path = (
        RAW_DIR
        / f"{split_label}_{MODEL_KEY}.json"
    )

    partial_path = (
        RAW_DIR
        / f"{split_label}_{MODEL_KEY}.partial.json"
    )

    expected_images = len(image_infos)

    # Gunakan ulang output final jika sudah lengkap.
    if output_path.exists() and not FORCE_REINFERENCE:
        raw = load_json(output_path)

        if len(raw) != expected_images:
            raise RuntimeError(
                f"Existing {split_label} prediction is incomplete: "
                f"{len(raw)} != {expected_images}"
            )

        expected_ids = {
            str(int(image["id"]))
            for image in image_infos
        }

        actual_ids = set(raw.keys())

        if actual_ids != expected_ids:
            raise RuntimeError(
                f"{split_label} image-ID coverage mismatch. "
                f"Missing={len(expected_ids - actual_ids)}, "
                f"extra={len(actual_ids - expected_ids)}"
            )

        print(
            f"✅ Raw prediction already complete: "
            f"{output_path}"
        )

        return raw

    # Lanjutkan dari file partial apabila tersedia.
    if partial_path.exists():
        raw = load_json(partial_path)

        print(
            f"♻️ Resuming {split_label} inference: "
            f"{len(raw)}/{expected_images} images completed"
        )
    else:
        raw = {}

    model.predictor = None

    for position, image_info in enumerate(
        image_infos,
        start=1,
    ):
        image_id = str(int(image_info["id"]))

        # Lewati gambar yang telah tersimpan di partial file.
        if image_id in raw:
            continue

        image_path = (
            DATASET_ROOT
            / split_directory
            / "images"
            / image_info["file_name"]
        )

        if not image_path.exists():
            raise FileNotFoundError(
                f"Image not found: {image_path}"
            )

        record = blank_record(image_info)

        result_count = 0

        # stream=True menghindari materialisasi seluruh Results.
        result_stream = model.predict(
            source=[str(image_path)],
            conf=0.001,
            iou=0.70,
            max_det=300,
            imgsz=IMAGE_SIZE,
            batch=1,
            device=DEVICE,
            augment=False,
            save=False,
            stream=True,
            verbose=False,
        )

        for result in result_stream:
            result_count += 1

            if result_count > 1:
                raise RuntimeError(
                    f"More than one result returned for: "
                    f"{image_path}"
                )

            if result.boxes is not None:
                boxes = (
                    result.boxes.xyxy
                    .detach()
                    .cpu()
                    .numpy()
                )

                scores = (
                    result.boxes.conf
                    .detach()
                    .cpu()
                    .numpy()
                )

                labels = (
                    result.boxes.cls
                    .detach()
                    .cpu()
                    .numpy()
                )

                for box, score, label in zip(
                    boxes,
                    scores,
                    labels,
                ):
                    x1, y1, x2, y2 = map(
                        float,
                        box,
                    )

                    if x2 <= x1 or y2 <= y1:
                        continue

                    record["boxes"].append([
                        x1,
                        y1,
                        x2,
                        y2,
                    ])

                    record["scores"].append(
                        float(score)
                    )

                    record["labels"].append(
                        int(label)
                    )

            del result

        if result_count != 1:
            raise RuntimeError(
                f"No prediction result returned for: "
                f"{image_path}"
            )

        raw[image_id] = record

        # Simpan progress secara berkala.
        if (
            position % 10 == 0
            or position == expected_images
        ):
            save_json(
                raw,
                partial_path,
            )

            print(
                f"{split_label}: "
                f"{len(raw)}/{expected_images} images saved"
            )

        gc.collect()

        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    expected_ids = {
        str(int(image["id"]))
        for image in image_infos
    }

    actual_ids = set(raw.keys())

    if actual_ids != expected_ids:
        raise RuntimeError(
            f"Final {split_label} coverage mismatch. "
            f"Missing={len(expected_ids - actual_ids)}, "
            f"extra={len(actual_ids - expected_ids)}"
        )

    save_json(
        raw,
        output_path,
    )

    if partial_path.exists():
        partial_path.unlink()

    print(
        f"✅ {split_label} raw predictions completed: "
        f"{len(raw)} images"
    )

    print(f"Saved to: {output_path}")

    return raw


def raw_to_coco_rows(raw):
    rows = []

    for record in raw.values():
        for box, score, label in zip(
            record["boxes"],
            record["scores"],
            record["labels"],
        ):
            x1, y1, x2, y2 = map(float, box)
            width = x2 - x1
            height = y2 - y1

            if width <= 0 or height <= 0:
                continue

            rows.append({
                "image_id": int(record["image_id"]),
                "category_id": int(label) + 1,
                "bbox": [x1, y1, width, height],
                "score": float(score),
            })

    return rows


def evaluate_common_coco(gt_path, raw):
    rows = raw_to_coco_rows(raw)

    if not rows:
        raise RuntimeError("No predictions for COCOeval.")

    with contextlib.redirect_stdout(io.StringIO()):
        coco_gt = COCO(str(gt_path))
        coco_dt = coco_gt.loadRes(rows)

        evaluator = COCOeval(
            coco_gt,
            coco_dt,
            "bbox",
        )
        evaluator.evaluate()
        evaluator.accumulate()
        evaluator.summarize()

    class_ap = {}

    for category_id, class_name in [
        (1, "coral"),
        (2, "fish"),
    ]:
        with contextlib.redirect_stdout(io.StringIO()):
            class_eval = COCOeval(
                coco_gt,
                coco_dt,
                "bbox",
            )
            class_eval.params.catIds = [
                category_id
            ]
            class_eval.evaluate()
            class_eval.accumulate()
            class_eval.summarize()

        class_ap[class_name] = float(
            class_eval.stats[0]
        )

    return {
        "mAP50_95": float(evaluator.stats[0]),
        "mAP50": float(evaluator.stats[1]),
        "mAP75": float(evaluator.stats[2]),
        "AP_coral": class_ap["coral"],
        "AP_fish": class_ap["fish"],
        "worst_class_AP": min(
            class_ap["coral"],
            class_ap["fish"],
        ),
        "detections": len(rows),
    }

In [12]:
# CELL 9 — GENERATE VALIDATION AND TEST RAW PREDICTIONS
inference_model = MODEL_CLASS(
    str(BEST_CHECKPOINT)
)

common_rows = []

for split_label in [
    "validation",
    "test",
]:
    raw = run_raw_inference(
        inference_model,
        split_label,
    )

    metrics = evaluate_common_coco(
        gt_path_for(split_label),
        raw,
    )

    common_rows.append({
        "protocol": PROTOCOL,
        "model": MODEL_KEY,
        "seed": SEED,
        "split": split_label,
        **metrics,
    })

common_df = pd.DataFrame(common_rows)
common_df.to_csv(
    RESULTS_DIR / "common_cocoeval_results.csv",
    index=False,
)

display(common_df)

validation: 10/232 images saved
validation: 20/232 images saved
validation: 30/232 images saved
validation: 40/232 images saved
validation: 50/232 images saved
validation: 60/232 images saved
validation: 70/232 images saved
validation: 80/232 images saved
validation: 90/232 images saved
validation: 100/232 images saved
validation: 110/232 images saved
validation: 120/232 images saved
validation: 130/232 images saved
validation: 140/232 images saved
validation: 150/232 images saved
validation: 160/232 images saved
validation: 170/232 images saved
validation: 180/232 images saved
validation: 190/232 images saved
validation: 200/232 images saved
validation: 210/232 images saved
validation: 220/232 images saved
validation: 230/232 images saved
validation: 232/232 images saved
✅ validation raw predictions completed: 232 images
Saved to: /content/drive/MyDrive/au-fish/dataset_v2/source_based/experiment_logs/multiseed_fullset_dedup_v1/individual/rtdetr_l/seed_2026/raw_predictions/validation_rtdetr_l.json
test: 10/231 images saved
test: 20/231 images saved
test: 30/231 images saved
test: 40/231 images saved
test: 50/231 images saved
test: 60/231 images saved
test: 70/231 images saved
test: 80/231 images saved
test: 90/231 images saved
test: 100/231 images saved
test: 110/231 images saved
test: 120/231 images saved
test: 130/231 images saved
test: 140/231 images saved
test: 150/231 images saved
test: 160/231 images saved
test: 170/231 images saved
test: 180/231 images saved
test: 190/231 images saved
test: 200/231 images saved
test: 210/231 images saved
test: 220/231 images saved
test: 230/231 images saved
test: 231/231 images saved
✅ test raw predictions completed: 231 images
Saved to: /content/drive/MyDrive/au-fish/dataset_v2/source_based/experiment_logs/multiseed_fullset_dedup_v1/individual/rtdetr_l/seed_2026/raw_predictions/test_rtdetr_l.json

,protocol,model,seed,split,mAP50_95,mAP50,mAP75,AP_coral,AP_fish,worst_class_AP,detections
0,source_based,rtdetr_l,2026,validation,0.295759,0.438221,0.315939,0.405095,0.186424,0.186424,69600
1,source_based,rtdetr_l,2026,test,0.261884,0.453805,0.253713,0.269740,0.254027,0.254027,69300

In [13]:
# CELL 10 — CHECKPOINT AND OUTPUT MANIFEST
manifest = {
    "protocol": PROTOCOL,
    "model": MODEL_KEY,
    "seed": SEED,
    "checkpoint_path": str(BEST_CHECKPOINT),
    "checkpoint_sha256": sha256_file(
        BEST_CHECKPOINT
    ),
    "dataset_yaml": str(YAML_PATH),
    "validation_raw_predictions": str(
        RAW_DIR
        / f"validation_{MODEL_KEY}.json"
    ),
    "test_raw_predictions": str(
        RAW_DIR
        / f"test_{MODEL_KEY}.json"
    ),
    "framework_native_results": str(
        RESULTS_DIR
        / "framework_native_results.csv"
    ),
    "common_cocoeval_results": str(
        RESULTS_DIR
        / "common_cocoeval_results.csv"
    ),
}

save_json(
    manifest,
    MANIFEST_DIR / "checkpoint_manifest.json",
)

required_outputs = [
    Path(manifest["checkpoint_path"]),
    Path(manifest["validation_raw_predictions"]),
    Path(manifest["test_raw_predictions"]),
    Path(manifest["framework_native_results"]),
    Path(manifest["common_cocoeval_results"]),
]

missing = [
    str(path)
    for path in required_outputs
    if not path.exists()
]

if missing:
    raise RuntimeError(
        "Missing final outputs:\n"
        + "\n".join(missing)
    )

print("✅ Individual multi-seed run complete.")
print("Run root:", RUN_ROOT)
print("Outputs are isolated by protocol/model/seed.")

✅ Individual multi-seed run complete.
Run root: /content/drive/MyDrive/au-fish/dataset_v2/source_based/experiment_logs/multiseed_fullset_dedup_v1/individual/rtdetr_l/seed_2026
Outputs are isolated by protocol/model/seed.

## Output structure

```text
{protocol}/
├── runs/multiseed_fullset_dedup_v1/{model}/seed_{seed}/train/
├── runs_eval/multiseed_fullset_dedup_v1/{model}/seed_{seed}/
└── experiment_logs/multiseed_fullset_dedup_v1/
    └── individual/{model}/seed_{seed}/
        ├── raw_predictions/
        ├── results/
        └── manifests/
```

Jangan memindahkan raw predictions ke folder seed lain. Pairwise WBF akan
membaca file berdasarkan protocol, model, dan seed yang sama.